// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4SzRM3Mkk1bldk6rr73j8RCUnry-FfMA',
    appId: '1:928524452734:web:a0d5ca6cb69c95c371292f',
    messagingSenderId: '928524452734',
    projectId: 'wired-maps-app2',
    authDomain: 'wired-maps-app2.firebaseapp.com',
    storageBucket: 'wired-maps-app2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWmKv-LBeavvZmO31fTs-ELpeASRZsmnQ',
    appId: '1:928524452734:android:58f0e37e81945fce71292f',
    messagingSenderId: '928524452734',
    projectId: 'wired-maps-app2',
    storageBucket: 'wired-maps-app2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCsrc7zCkSOx1J_oOde4K6_mTA7xD1qjU',
    appId: '1:928524452734:ios:916226a5f9f377ce71292f',
    messagingSenderId: '928524452734',
    projectId: 'wired-maps-app2',
    storageBucket: 'wired-maps-app2.appspot.com',
    iosClientId: '928524452734-0eqsalg26lpphv25e66mk6grf05es69p.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCsrc7zCkSOx1J_oOde4K6_mTA7xD1qjU',
    appId: '1:928524452734:ios:916226a5f9f377ce71292f',
    messagingSenderId: '928524452734',
    projectId: 'wired-maps-app2',
    storageBucket: 'wired-maps-app2.appspot.com',
    iosClientId: '928524452734-0eqsalg26lpphv25e66mk6grf05es69p.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );
}
