// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyrRMjFSjb21ZuTr3xuJmCkfPZz0Jqopo',
    appId: '1:793456833549:web:4a8f4377e609382fc21144',
    messagingSenderId: '793456833549',
    projectId: 'wire-maps',
    authDomain: 'wire-maps.firebaseapp.com',
    storageBucket: 'wire-maps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKRPzcn0BMzH4_QI7GN0Sd2V1I28nFpk',
    appId: '1:793456833549:android:23173a9f7bf989e4c21144',
    messagingSenderId: '793456833549',
    projectId: 'wire-maps',
    storageBucket: 'wire-maps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhFrI6WUYcg2CX_QTzXvE-SfnZcIk1EtY',
    appId: '1:793456833549:ios:bd4e70dec607331ec21144',
    messagingSenderId: '793456833549',
    projectId: 'wire-maps',
    storageBucket: 'wire-maps.appspot.com',
    iosClientId: '793456833549-452c67g4vovrgg2gtooneislqh9jht3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhFrI6WUYcg2CX_QTzXvE-SfnZcIk1EtY',
    appId: '1:793456833549:ios:bd4e70dec607331ec21144',
    messagingSenderId: '793456833549',
    projectId: 'wire-maps',
    storageBucket: 'wire-maps.appspot.com',
    iosClientId: '793456833549-452c67g4vovrgg2gtooneislqh9jht3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );
}
